### ISSUE TITLE
Installation wizard fails to install python dependencies

### ISSUE THREAD

**Issue by NO-BOOT-DEVICE-DETECTED** [intel/AI-Playground#108]
## To Reproduce

1. Go to https://github.com/intel/AI-Playground/releases/download/v1.22beta/AI.Playground-1.22.1beta-Arc-dGPU_ACM.exe 
dowload and execute
3. follow default installation steps
4. Run AI Playground
5. See error: Backend initialization failed
The AI inference backend failed to initialize. Please try restarting the application. If the problem persists, you can check the Details for additional information about the error.
Details
Open Log
`ModuleNotFoundError: No module named 'flask'
`
## Expected behavior

Program starts and executes normally

## Environment (please complete the following information):

- OS: [e.g. Windows10]
- GPU: [e.g. Intel Arc A770 16G]
- CPU: [e.g. r5 5600x]
- Version: [e.g. v1.22.2beta-Arc-dGPU_ACM]

## Additional context

The installation wizard prompts the user asking to install python dependencies. After allowing my clicking 'ok', the console reports that it attempts to install said dependencies, but an error occurs and the wizard finishes. The program can start, but only gives a backend initialization error.

I have been unable to see the error in the installation console, since once it is printed, the wizard moves to the successful installation screen and I cannot access the installation log. The best that I was able to read was a line that read 'This error was most likely caused by a subproscess, and not pip.' and something about how it failed to get metadata or something. I'm sorry, this is really the best I was able to make out after several installation attempts.

**Comment by Nuullll** [comment]
Duplicated with https://github.com/intel/AI-Playground/issues/93

**Comment by NO-BOOT-DEVICE-DETECTED** [comment]
> Duplicated with #93

Following the steps in #93, I was able to get the complete error text that I could not in the installer. 
This is the complete output of the command line:
`Looking in indexes: https://pypi.org/simple, https://pytorch-extension.intel.com/release-whl/stable/xpu/us/, https://pytorch-extension.intel.com/release-whl/stable/xpu/cn/
Collecting basicsr==1.4.2 (from -r C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\service\requirements.txt (line 1))
  Using cached basicsr-1.4.2.tar.gz (172 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Frank Wankerl\AppData\Local\Temp\pip-install-gvijdnpr\basicsr_c39589db35c9429b98fd9cef95edbd21\setup.py", line 147, in <module>
          setup(
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\__init__.py", line 116, in setup
          _install_setup_requires(attrs)
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\__init__.py", line 89, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\__init__.py", line 94, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\dist.py", line 664, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\installer.py", line 40, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\pkg_resources\__init__.py", line 897, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\pkg_resources\__init__.py", line 933, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\pkg_resources\__init__.py", line 1271, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\pkg_resources\__init__.py", line 1307, in obtain
          return installer(requirement) if installer else None
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\installer.py", line 108, in _fetch_build_egg_no_warn
          wheel.install_as_egg(dist_location)
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\wheel.py", line 122, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\wheel.py", line 130, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\wheel.py", line 150, in _convert_metadata
          _unpack_zipfile_obj(zf, destination_eggdir)
        File "C:\Users\Frank Wankerl\AppData\Local\Programs\AI Playground\resources\env\Lib\site-packages\setuptools\archive_util.py", line 131, in _unpack_zipfile_obj
          with open(target, 'wb') as f:
               ^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Frank Wankerl\\AppData\\Local\\Temp\\pip-install-gvijdnpr\\basicsr_c39589db35c9429b98fd9cef95edbd21\\.eggs\\torch-2.5.1-py3.11-win-amd64.egg\\torch\\include\\ATen\\ops\\_scaled_dot_product_fused_attention_overrideable_backward_compositeexplicitautograd_dispatch.h'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by Nuullll** [comment]
@NO-BOOT-DEVICE-DETECTED thanks for providing the details
Seems related to windows path length limitation: https://github.com/intel/AI-Playground/issues/69#issuecomment-2407933138

**Comment by NO-BOOT-DEVICE-DETECTED** [comment]
> @NO-BOOT-DEVICE-DETECTED thanks for providing the details Seems related to windows path length limitation: [#69 (comment)](https://github.com/intel/AI-Playground/issues/69#issuecomment-2407933138)

Thanks for the help.
I needed to implment both the solutions in #93 and #69 to get the program operational
